name: Tests
on:
  push:
    branches:
      - main
    paths:
      - "**.php"
      - "**.tsx"
      - "**.ts"
  workflow_dispatch:

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          tools: composer, cs2pr, phpcs

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.8.0'

      - name: Start WordPress Environment
        run: pnpm run wp-env start --xdebug=coverage
  
      - name: Check WooCommerce Activation
        run: pnpm run wp-env run cli -- wp plugin list

      - name: Linting the code
        run: |
          vendor/bin/phpcs -i
          vendor/bin/phpcs --config-show
          # vendor/bin/phpcs --report=checkstyle | cs2pr
          pnpm run lint
        continue-on-error: true

      - name: Running the tests
        run: | 
          pnpm run test
          # cat phpunit.xml | cs2pr
