name: Deploy to WP Engine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: |
          yarn install
          composer prefix-dependencies
          composer install --no-dev
          yarn build:js

      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: wcposdev
          REMOTE_PATH: "wp-content/plugins/woocommerce-pos"
          FLAGS: >-
            -azvr --inplace --delete --delete-excluded --exclude-from=.distignore
            -e "ssh -o StrictHostKeyChecking=no -o ControlMaster=no -p 22 -i /github/home/.ssh/wpe_id_rsa"
          CACHE_CLEAR: TRUE