name: Deploy to WordPress.org

on:
  release:
    types: [ released ]
  workflow_dispatch:

jobs:
  tag:
    name: New release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: |
          yarn install
          composer prefix-dependencies
          composer install --no-dev
          yarn build:js

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: woocommerce-pos
        continue-on-error: true
